//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.02 at 09:48:16 PM IST 
//


package org.w3._2000._09.xmldsig_;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.w3._2000._09.xmldsig_ package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.w3._2000._09.xmldsig_
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Signature }
     * 
     */
    public Signature createSignature() {
        return new Signature();
    }

    /**
     * Create an instance of {@link Signature.SignedInfo }
     * 
     */
    public Signature.SignedInfo createSignatureSignedInfo() {
        return new Signature.SignedInfo();
    }

    /**
     * Create an instance of {@link Signature.SignedInfo.Reference }
     * 
     */
    public Signature.SignedInfo.Reference createSignatureSignedInfoReference() {
        return new Signature.SignedInfo.Reference();
    }

    /**
     * Create an instance of {@link Signature.SignedInfo.Reference.Transforms }
     * 
     */
    public Signature.SignedInfo.Reference.Transforms createSignatureSignedInfoReferenceTransforms() {
        return new Signature.SignedInfo.Reference.Transforms();
    }

    /**
     * Create an instance of {@link Signature.SignedInfo.CanonicalizationMethod }
     * 
     */
    public Signature.SignedInfo.CanonicalizationMethod createSignatureSignedInfoCanonicalizationMethod() {
        return new Signature.SignedInfo.CanonicalizationMethod();
    }

    /**
     * Create an instance of {@link Signature.SignedInfo.SignatureMethod }
     * 
     */
    public Signature.SignedInfo.SignatureMethod createSignatureSignedInfoSignatureMethod() {
        return new Signature.SignedInfo.SignatureMethod();
    }

    /**
     * Create an instance of {@link Signature.SignedInfo.Reference.DigestMethod }
     * 
     */
    public Signature.SignedInfo.Reference.DigestMethod createSignatureSignedInfoReferenceDigestMethod() {
        return new Signature.SignedInfo.Reference.DigestMethod();
    }

    /**
     * Create an instance of {@link Signature.SignedInfo.Reference.Transforms.Transform }
     * 
     */
    public Signature.SignedInfo.Reference.Transforms.Transform createSignatureSignedInfoReferenceTransformsTransform() {
        return new Signature.SignedInfo.Reference.Transforms.Transform();
    }

}
